filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    multiline.pattern: '^\['
    multiline.negate: true
    multiline.match: after

processors:
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]